# Generated by Django 5.2.4 on 2025-07-26 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('etat', models.CharField(choices=[('neuf', 'Neuf'), ('utilisé', 'Utilisé'), ('HS', 'Hors service')], max_length=50)),
                ('date_achat', models.DateField(blank=True, null=True)),
                ('localisation', models.CharField(blank=True, max_length=100)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Inventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantite', models.PositiveIntegerField()),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.materiel')),
            ],
        ),
        migrations.CreateModel(
            name='Mouvement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie'), ('transfert', 'Transfert')], max_length=20)),
                ('quantite', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.materiel')),
                ('operateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
